name: state_machine_animation
description: State-machine driven animation controller and evaluation library based on streams.
version: 1.0.2
repository: https://github.com/Zira-Games/state-machine-animation
homepage: https://github.com/Zira-Games/state-machine-animation

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5
  equatable: ^2.0.5
  belatuk_merge_map: ^3.0.0
  memoized: ^1.5.0
  clock: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
